---

- hosts: all
  become: true
  tasks:

  - name: run update and install latest apache and php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
