---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache OS Family Debian
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_os_family == "Debian"

  - name: updates repo cache OS Family RedHat
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_os_family == "RedHat"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINiIaQ3H9IKsIwxeD4hPvCuGJ2RCGrnxrDNt/thgWGUf mehrentraut@NANX0AS50363"

- hosts: web_servers
  become: true
  tasks:

  - name: run update and install latest apache and php
    tags: apache,apache2,httpd
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

  - name: httpd is running and enabled
    service:
      name: "{{ service_package }}"
      state: started
      enabled: yes

  - name: change email address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin admin@phoenyx.me
    when: ansible_os_family == "RedHat"
    register: httpd

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy website to server
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: Check Firewall on CentOS and open Port 80 for httpd
    tags: apache,apache2,httpd,firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true
    when: ansible_os_family == "RedHat"

  - name: Check Firewall on CentOS and open Port 443 for httpd
    tags: apache,apache2,httpd,firewall
    firewalld:
      service: https
      permanent: true
      state: enabled
      immediate: true
    when: ansible_os_family == "RedHat"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: mariadb,ubuntu,centos,db
    package:
      name:
        - "{{ db_package }}"
      state: latest

  - name: mariadb is running and enabled
    service:
      name: mariadb
      state: started
      enabled: yes

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
